# Generated by Django 4.0.6 on 2022-08-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isoCode', models.CharField(max_length=10)),
                ('callingCode', models.CharField(max_length=10)),
                ('flag', models.CharField(max_length=300)),
                ('capital', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
            ],
        ),
    ]
